### ISSUE TITLE
Incompatible with Windows <10

### ISSUE THREAD

**Issue by namazso** [RiotVanguard/Vanguard#14]
RtlFindExportedRoutineByName is not exported until Windows 10. I hope you can fix this serious problem!

**Comment by vmcall** [comment]
+1 doesn't work on my own compilation of xp

**Comment by itsgamerdoc** [comment]
We will fix this soon as we can thank you, we will make sure its compatible for windows 98

**Comment by staticinvocation** [comment]
Contributions welcome!

**Comment by RiotVanguard** [comment]
It's open source. If you don't like it, please make a PR and we will fix it. ⚡

**Comment by namazso** [comment]
how's the pay tho

**Comment by itsgamerdoc** [comment]
> how's the pay tho

what pay

**Comment by 0xGREG** [comment]
> > how's the pay tho
> 
> what pay

Pay deez nuts gotem

**Comment by VgkDeliveryBoi** [comment]
I think this is worth the 100k bounty Riot offered. PAY THE GUY DAMMIT.
What a scam

**Comment by hzswdef** [comment]
> It's open source. If you don't like it, please make a PR and we will fix it. ⚡

Lie. 0 merged PRs ;)

Hi @VgkDeliveryBoi
