### ISSUE TITLE
Aimware is no longer injecting

### ISSUE THREAD

**Issue by quadruple-damage** [RiotVanguard/Vanguard#23]
after installing this soft ware aimware has stopped injecting into cs:go
please fix this as soon as you can possibly can because i want to hvh in counter-strike: global offensive with whats left of my friends after around 41% have commited suicide

**Comment by Crystallinqq** [comment]
You are permanently banned from AIMWARE. Contact an administrator.

**Comment by kekw-420** [comment]
config error. thread closed. banned for racism

**Comment by aholic1208** [comment]
bad faith

**Comment by douglasb78** [comment]
> You are permanently banned from AIMWARE. Contact an administrator.

best crystal pvper

**Comment by quadruple-damage** [comment]
as of latest updatem aimware injects. thank u badster

**Comment by poIak** [comment]
please pm me on the forums
